### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Kupo91** [maloep/romcollectionbrowser#395]
I can't run any games with dolphin. If I select a game and try to start it nothing happens.
This is what the logfile says:

```
2019-03-05 19:10:01.520 T:139919557125888   DEBUG: RCB_INFO launcher.buildCmd
2019-03-05 19:10:01.520 T:139919557125888   DEBUG: RCB_INFO emuCommandLine: /storage/.kodi/userdata/addon_data/script.games.rom.collection.browser/scriptfiles/dolphin.start
2019-03-05 19:10:01.520 T:139919557125888   DEBUG: RCB_INFO preCmdLine:
2019-03-05 19:10:01.520 T:139919557125888   DEBUG: RCB_INFO postCmdLine:
2019-03-05 19:10:01.520 T:139919557125888   DEBUG: RCB_INFO Getting Multiple Disc Parameter
2019-03-05 19:10:01.523 T:139919557125888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xa0' in position 21: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.games.rom.collection.browser/resources/lib/gui.py", line 365, in onClick
                                                self.launchEmu()
                                              File "/storage/.kodi/addons/script.games.rom.collection.browser/resources/lib/gui.py", line 1017, in launchEmu
                                                launcher.launchEmu(self.gdb, self, gameId, self.config, selectedGame)
                                              File "/storage/.kodi/addons/script.games.rom.collection.browser/resources/lib/launcher.py", line 47, in launchEmu
                                                cmd, precmd, postcmd, roms = self._buildCmd(gui, filenameRows, gameRow, False)
                                              File "/storage/.kodi/addons/script.games.rom.collection.browser/resources/lib/launcher.py", line 145, in _buildCmd
                                                match = re.search(self.romCollection.diskPrefix.lower(), str(gamename).lower())
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 21: ordinal not in range(128)
                                            -->End of Python script error report<--
2019-03-05 19:10:01.523 T:139919557125888   DEBUG: RCB_INFO: onAction: 7
2019-03-05 19:10:19.589 T:139920001240384   DEBUG: Keyboard: scancode: 0x09, sym: 0x001b, unicode: 0x001b, modifier: 0x0
2019-03-05 19:10:19.723 T:139920001240384   DEBUG: Keyboard: scancode: 0x09, sym: 0x001b, unicode: 0x0000, modifier: 0x0
2019-03-05 19:10:19.723 T:139920001240384   DEBUG: HandleKey: escape (0xf01b) pressed, action is PreviousMenu
2019-03-05 19:10:19.723 T:139919557125888   DEBUG: RCB_INFO: onAction: 10
2019-03-05 19:10:19.723 T:139919557125888   DEBUG: RCB_INFO: onAction: ACTION_CANCEL_DIALOG
2019-03-05 19:10:19.723 T:139919557125888   DEBUG: RCB_INFO: exit
2019-03-05 19:10:19.723 T:139919557125888   DEBUG: RCB_INFO: Begin saveViewState
2019-03-05 19:10:19.742 T:139919557125888   DEBUG: RCB_INFO: Begin saveViewMode
```

Maybe the same issue like this https://github.com/maloep/romcollectionbrowser/issues/202

**Comment by Kupo91** [comment]
I could solved this issue by myself. I only had one wii game so I thought its a general wii issue but it is not. To scrape my wii rom properly I copied the name of the game from thegamesdb.net
Apparently there is some sort of invinsible special character in the name that caused this issue.
RCB didnt create a nfo file aswell but still showed the content as publisher, release date and description.
It also didnt show the artworks, not just at this game but also at other wii games. I dont know what exactly was the issue for that because I generally have issues to refresh artworks in RCB. I removed mygames.db and also cleared and reloaded my cache with Texture Cache Maintenance Utility without success. It still showed my old artworks. However removing the thumbs folder and the textures database manually solved this issue. So maybe it was a combination of two different issues. Not sure, just happy that everything works know.
