### ISSUE TITLE
Issue with the launchCount / emulator wont run

### ISSUE THREAD

**Issue by ochi-man** [maloep/romcollectionbrowser#414]
When try to launch any rom, it wont start and point the error to the file launcher.py, i run python2 launcher.py in terminal and it runs fine (probably because the error part dont run that way) 

I am using the leia branche, but got error with others too (i try the stable before, dont know if the error in the stable is the same)

the error message points to something wrong with the launch count, i just commented out and now its starting the roms.

line 88 of ~/.kodi/addons/script.games.rom.collection.browser/resources/lib/launcher.py
  `     # Game(gdb).update(('launchCount',), (launchCount + 1,), gameRow[Game.COL_ID], True)`

```
2020-04-14 00:15:39.807 T:139669916350208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: unsupported operand type(s) for +: 'NoneType' and 'int'
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/script.games.rom.collection.browser/resources/lib/gui.py", line 365, in onClick
                                                self.launchEmu()
                                              File "/var/lib/kodi/.kodi/addons/script.games.rom.collection.browser/resources/lib/gui.py", line 992, in launchEmu
                                                launcher.launchEmu(self.gdb, self, gameId, self.config, selectedGame)
                                              File "/var/lib/kodi/.kodi/addons/script.games.rom.collection.browser/resources/lib/launcher.py", line 88, in launchEmu
                                                Game(gdb).update(('launchCount',), (launchCount + 1,), gameRow[Game.COL_ID], True)
                                            TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
                                            -->End of Python script error report<--
2020-04-14 00:15:39.808 T:139669916350208   DEBUG: RCB_INFO: onAction: 7
```

If you need some more info i would be happy to help.

**Comment by maloep** [comment]
Fixed with 61c11f109c53bf7768430c4eca4dffa4cbf5b1b5
Update master (Matrix) and Leia branch
